"""Add shift period table

Revision ID: 63f1c50bc8e3
Revises: bf2b8caa5808
Create Date: 2024-08-29 10:05:06.736605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f1c50bc8e3'
down_revision: Union[str, None] = 'bf2b8caa5808'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_shift_creation_periods_id', table_name='shift_creation_periods')
    op.drop_table('shift_creation_periods')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shift_creation_periods',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_shift_creation_periods_id', 'shift_creation_periods', ['id'], unique=False)
    # ### end Alembic commands ###
