"""Add ShiftCreationPeriod model

Revision ID: bf2b8caa5808
Revises: c5111f40fb4d
Create Date: 2024-08-29 09:26:55.440519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2b8caa5808'
down_revision: Union[str, None] = 'c5111f40fb4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'shift_requests_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('shift_requests_count', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
